server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/productdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    user:
      name: root
      password: root

jwt:
  public-key-location: classpath:public.pem
